mode: host
name: admin
branch: master
setup: 
- npm i
trigger:
  - name: project
    value: web
    changes:
    - /web/*
flow:
- install
- build-app
- test-app
- build-server
steps:
  install:
    trigger:
    - changes:
      - package.json
      - package-lock.json
    cmd:
    - npm i
  build-app:
    cmd:
    - npm run build-app ${project}
  test-app:
    cmd:
    - npm test
  build-server: 
    cmd:
    - npm run build-server
deploy:
  path: /${project}/
  target: kubernetes
  kubernetes:
    type: deploy
    namespace: dev
    name: admin
    containerName: admin
    image: asia.gcr.io/project-iddddd/admin:latest
webhooks:
- type: slack
  url: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
  prefix: "*[ ${repo}/${branch} ]*"