FROM formulaci-base
RUN apk --no-cache add build-base
RUN go get github.com/gorilla/websocket && \
 go get github.com/mattn/go-sqlite3 && \
 go install github.com/mattn/go-sqlite3 && \
 go get gopkg.in/yaml.v2 && \
 go get github.com/gobwas/glob && \
 go get github.com/NeoJRotary/describe-go
